# Example services.yaml entry

# Service ID
send_message:
  # Service name as shown in UI
  name: send_message
  # Description of the service
  description: Send a notification to a specific target.
  # If the service accepts entity IDs, target allows the user to specify entities by entity, device, or area. If `target` is specified, `entity_id` should not be defined in the `fields` map. By default it shows only targets matching entities from the same domain as the service, but if further customization is required, target supports the entity, device, and area selectors (https://www.home-assistant.io/docs/blueprint/selectors/). Entity selector parameters will automatically be applied to device and area, and device selector parameters will automatically be applied to area.
  # Different fields that your service accepts
  fields:
    # Key of the field
    message:
      # Field name as shown in UI
      name: message
      # Description of the field
      description: Message  of the notification.
      # Whether or not field is required (default = false)
      required: true
      # Advanced fields are only shown when the advanced mode is enabled for the user (default = false)
      advanced: true
      # Example value that can be passed for this field
      example: "warrning door open"
      # The default field value
      default: "hello"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        text:
    image:
      # Field name as shown in UI
      name: image
      # Description of the field
      description: image ture/false
      # Whether or not field is required (default = false)
      required: true
      # Advanced fields are only shown when the advanced mode is enabled for the user (default = false)
      advanced: true
      # The default field value
      default: false
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        boolean: